#!/bin/zsh

# reset zsh options
emulate -LR zsh

# read session cookie from file
day=$(date +'%d')
source session

# get current day, create directory and chage to it
day=$(date +'%d')
mkdir $day
cd $day

# create code files
touch day${day}.py
touch day${day}_test.py
touch test_input.txt

# download input
curl https://adventofcode.com/2021/day/${day}/input --cookie "session=${session}" > input.txt

